from playwright.sync_api import sync_playwright
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('http://127.0.0.1:5500/techo-stats.html')
    login = page.locator('#username')
    login.fill('tzadmin')
    password = page.locator('#password')
    password.fill('1')
    button = page.locator('#btn_log')
    button.click()
    user_list = page.locator('#userListBtn')
    user_list.click()
    create_user = page.locator('#createUserBtn')
    create_user.click()
    new_user = page.locator('#newUserFIO')
    new_user.fill('Попов Антон Николаевич')
    user_phone = page.locator('#newUserPhone')
    user_phone.fill('89090104904')
    email = page.locator('#newUserEmail')
    email.fill('tzzelen@my.net')
    new_username = page.locator('#newUsername')
    new_username.fill('Павел Александрович')
    new_password = page.locator('#newPassword')
    new_password.fill('1')
    page.select_option('#newUserRole')  # выбор локатора
    page.select_option('#newUserRole', 'admin')
    confirm = page.locator('#userFormSubmitBtn')
    confirm.click()
    alert = page.locator('#customAlertOkBtn')
    alert.click()
    close_btn = page.locator('#closeModalBtn')
    close_btn.click()
    create_state = page.get_by_role("button", name="Создать статью")
    create_state.click()
    articleTitle = page.locator('#articleTitle')
    articleTitle.fill('test')
    headerText = page.locator('#headerText')
    headerText.fill('test')
    write = page.locator('div.ck-editor__editable_inline')
    write.fill('test')
    submit = page.get_by_role("button", name="Сохранить")
    submit.click()
    page.reload()
    storage = page.get_by_role("button", name="Перейти в хранилище")
    storage.click()
    create_button = page.locator('#create-folder-btn')
    create_button.click()
    folderName = page.locator('#folderName')
    folderName.fill('test')
    checkbox = page.locator('#isProtectedCheckbox')
    checkbox.click()
    folderPassword = page.locator('#folderPassword')
    folderPassword.fill('1')
    save_btn = page.locator('#createFolderbutton')
    save_btn.click()
    createstateboss = page.locator('#createstateboss')
    createstateboss.click()
    articleTitle2 = page.locator('#articleTitle')
    articleTitle2.fill('Test lock folder')
    write2 = page.locator('div.ck-editor__editable_inline')
    write2.fill('test')
    saveButtonState = page.get_by_role("button", name="Сохранить")
    saveButtonState.click()
    userAvatarMenuBtn = page.locator('#userAvatarMenuBtn')
    userAvatarMenuBtn.click()
    cabinet = page.locator('#cabinet-nav-btn')
    cabinet.click()
    editCabinetBtn = page.locator('#editCabinetBtn')
    editCabinetBtn.click()
    cabinetFio = page.locator('#cabinetFio')
    cabinetFio.fill('test')
    saveCabinetBtn = page.locator('#saveCabinetBtn')
    saveCabinetBtn.click()
    customAlertOkBtn = page.locator('#customAlertOkBtn')
    customAlertOkBtn.click()
    gue = page.get_by_role("button", name="На главную")
    gue.click()
    userAvatarMenuBtn2 = page.locator('#userAvatarMenuBtn')
    userAvatarMenuBtn2.click()
    logoutBtnFromMenu = page.locator('#logoutBtnFromMenu')
    logoutBtnFromMenu.click()
    page.reload()
    accessBtn = page.locator('#accessBtn')
    accessBtn.click()
    requestAccountBtn = page.locator('#requestAccountBtn')
    requestAccountBtn.click()
    requestFio = page.locator('#requestFio')
    requestFio.fill('Горин Генадий Алексеевич')
    requestPhone = page.locator('#requestPhone')
    requestPhone.fill('89090000000')
    requestEmail = page.locator('#requestEmail')
    requestEmail.fill('admin@mail.ru')
    requestReason =page.locator('#requestReason')
    requestReason.fill('lorem')
    submitBtnCheck = page.get_by_role("button", name='Отправить')
    submitBtnCheck.click()
    customAlertOkBtn = page.locator('#customAlertOkBtn')
    customAlertOkBtn.click()
    print('Успех!')



    # page.wait_for_timeout(5000)

